col = ['amount', 'age', '..>= 200 DM/salary for at least 1 year',
       '0<=..<200 DM', 'no checking account',
       'critical account/other credits elsewhere',
       'delay in paying off in the past',
       'existing credits paid back duly till now',
       'no credits taken/all credits paid back duly', 'car (new)',
       'car (used)', 'domestic appliances', 'furniture/equipment', 'others',
       'radio/television', 'repairs', 'retraining', 'vacation', '..>=1000 DM',
       '100<=..<500 DM', '500<=..<1000 DM', 'unknown/no savings account',
       '25<=..<35', '<20', '>=35', '4<=..<7 yrs', '<1 yr', '>=7 yrs',
       'unemployed', 'female : single', 'male : divorced/separated',
       'male : married/widowed', 'co-applicant', 'guarantor', '4<=..<7 yrs',
       '<1 yr', '>=7 yrs', 'car or other', 'real estate',
       'unknown / no property', 'none', 'stores', 'own', 'rent', '2-3', '4-5',
       '>= 6', 'skilled employee/official',
       'unemployed/unskilled - non-resident', 'unskilled - resident',
       '3 or more', 'Yes', 'yes']